# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1.0, help_text='Quantity of plant offered for the trade')),
                ('quantity_units', models.CharField(choices=[(1, 'Individual plants'), (2, 'Kilograms')], help_text='Quantity units for plant offered for trade', max_length=32)),
                ('will_post', models.BooleanField(default=False, help_text='Designates whether the user is willing to post the item(s)')),
                ('pick_your_own', models.BooleanField(default=False, help_text='Allow traders to harvest the plant(s) themselves, from your garden')),
                ('is_free', models.BooleanField(default=False, help_text='Give the item(s) away for free')),
                ('accept_offers', models.BooleanField(default=True, help_text='Accept offers of any other plant(s)')),
                ('wanted_quantity', models.FloatField(blank=True, default=1.0, help_text='Quantity of plant wanted for the trade', null=True)),
                ('wanted_quantity_units', models.CharField(blank=True, choices=[(1, 'Individual plants'), (2, 'Kilograms')], help_text='The units to be used for the quantity of wanted plants', max_length=32, null=True)),
                ('comments', models.TextField()),
            ],
        ),
    ]
