# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20170505_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
